In [3]:
import numpy as np
import pandas as pd
import ast

In [4]:
movies=pd.read_csv("tmdb_5000_movies.csv")
credits=pd.read_csv("tmdb_5000_credits.csv")

In [5]:
movies.shape

(4803, 20)

In [6]:
credits.shape

(4803, 4)

In [7]:
movies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4803 entries, 0 to 4802
Data columns (total 20 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   budget                4803 non-null   int64
 1   genres                4803 non-null   object
 2   homepage              1712 non-null   object
 3   id                    4803 non-null   int64
 4   keywords              4803 non-null   object
 5   original_language     4803 non-null   object
 6   original_title        4803 non-null   object
 7   overview              4800 non-null   object
 8   popularity            4803 non-null   float64
 9   production_companies  4803 non-null   object
 10  production_countries  4803 non-null   object
 11  release_date          4802 non-null   object
 12  revenue               4803 non-null   int64
 13  runtime               4801 non-null   float64
 14  spoken_languages      4803 non-null   object
 15  status                4803 non-null   object
 16  tagline               3959 non-null   object
 17  title                 4803 non-null   object
 18  vote_average          4803 non-null   float64
 19  vote_count            4803 non-null   int64
dtypes: float64(3), int64(4), object(13)
memory usage: 750.6+ KB

In [8]:
# merging the 2 dataset together based of title
movies=movies.merge(credits,on="title")

In [9]:
movies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4809 entries, 0 to 4808
Data columns (total 23 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   budget                4809 non-null   int64
 1   genres                4809 non-null   object
 2   homepage              1713 non-null   object
 3   id                    4809 non-null   int64
 4   keywords              4809 non-null   object
 5   original_language     4809 non-null   object
 6   original_title        4809 non-null   object
 7   overview              4806 non-null   object
 8   popularity            4809 non-null   float64
 9   production_companies  4809 non-null   object
 10  production_countries  4809 non-null   object
 11  release_date          4808 non-null   object
 12  revenue               4809 non-null   int64
 13  runtime               4807 non-null   float64
 14  spoken_languages      4809 non-null   object
 15  status                4809 non-null   object
 16  tagline               3965 non-null   object
 17  title                 4809 non-null   object
 18  vote_average          4809 non-null   float64
 19  vote_count            4809 non-null   int64
 20  movie_id              4809 non-null   int64
 21  cast                  4809 non-null   object
 22  crew                  4809 non-null   object
dtypes: float64(3), int64(5), object(15)
memory usage: 864.2+ KB

In [10]:
#Keeping relevent columns 
#generes
#id
#title
#keywords
#overview
#cast
#crew
movies=movies[['genres','id','title','keywords','overview','cast','crew']]

In [11]:
movies.head(1)

                                              genres  ...                                               crew
0  [{"id": 28, "name": "Action"}, {"id": 12, "nam...  ...  [{"credit_id": "52fe48009251416c750aca23", "de...

[1 rows x 7 columns]

In [12]:
movies.isnull().sum()

genres      0
id          0
title       0
keywords    0
overview    3
cast        0
crew        0
dtype: int64

In [13]:
movies.dropna(inplace=True)

In [14]:
movies.duplicated().sum()

np.int64(0)

In [15]:
def convert(obj):
    L=[]
    for i in ast.literal_eval(obj):
        L.append(i['name'])
    return L

In [16]:
movies['genres']=movies['genres'].apply(convert)

In [17]:
movies['keywords']=movies['keywords'].apply(convert)

In [18]:
movies.head()

                                          genres  ...                                               crew
0  [Action, Adventure, Fantasy, Science Fiction]  ...  [{"credit_id": "52fe48009251416c750aca23", "de...
1                   [Adventure, Fantasy, Action]  ...  [{"credit_id": "52fe4232c3a36847f800b579", "de...
2                     [Action, Adventure, Crime]  ...  [{"credit_id": "54805967c3a36829b5002c41", "de...
3               [Action, Crime, Drama, Thriller]  ...  [{"credit_id": "52fe4781c3a36847f81398c3", "de...
4           [Action, Adventure, Science Fiction]  ...  [{"credit_id": "52fe479ac3a36847f813eaa3", "de...

[5 rows x 7 columns]

In [19]:
def convert3(obj):
    L=[]
    count=0
    for i in ast.literal_eval(obj):
        if count!=3 :
            L.append(i['name'])
            count+=1
        else:
            break
    return L

In [20]:
movies["cast"]=movies['cast'].apply(convert3)

In [21]:
movies.head()

                                          genres  ...                                               crew
0  [Action, Adventure, Fantasy, Science Fiction]  ...  [{"credit_id": "52fe48009251416c750aca23", "de...
1                   [Adventure, Fantasy, Action]  ...  [{"credit_id": "52fe4232c3a36847f800b579", "de...
2                     [Action, Adventure, Crime]  ...  [{"credit_id": "54805967c3a36829b5002c41", "de...
3               [Action, Crime, Drama, Thriller]  ...  [{"credit_id": "52fe4781c3a36847f81398c3", "de...
4           [Action, Adventure, Science Fiction]  ...  [{"credit_id": "52fe479ac3a36847f813eaa3", "de...

[5 rows x 7 columns]

In [22]:
def fectch_dir(obj):
    L=[]
    for i in ast.literal_eval(obj):
        if i['job']=='Director' :
            L.append(i['name'])
            break
    return L

In [23]:
movies['crew']=movies['crew'].apply(fectch_dir)

In [24]:
movies.head()

                                          genres  ...                 crew
0  [Action, Adventure, Fantasy, Science Fiction]  ...      [James Cameron]
1                   [Adventure, Fantasy, Action]  ...     [Gore Verbinski]
2                     [Action, Adventure, Crime]  ...         [Sam Mendes]
3               [Action, Crime, Drama, Thriller]  ...  [Christopher Nolan]
4           [Action, Adventure, Science Fiction]  ...     [Andrew Stanton]

[5 rows x 7 columns]

In [25]:
movies['overview']=movies['overview'].apply(lambda x:x.split())

In [26]:
movies.head()

                                          genres  ...                 crew
0  [Action, Adventure, Fantasy, Science Fiction]  ...      [James Cameron]
1                   [Adventure, Fantasy, Action]  ...     [Gore Verbinski]
2                     [Action, Adventure, Crime]  ...         [Sam Mendes]
3               [Action, Crime, Drama, Thriller]  ...  [Christopher Nolan]
4           [Action, Adventure, Science Fiction]  ...     [Andrew Stanton]

[5 rows x 7 columns]

In [27]:
movies['genres']=movies['genres'].apply(lambda x:[i.replace(" ","") for i in x])
movies['keywords']=movies['keywords'].apply(lambda x:[i.replace(" ","") for i in x])
movies['cast']=movies['cast'].apply(lambda x:[i.replace(" ","") for i in x])
movies['crew']=movies['crew'].apply(lambda x:[i.replace(" ","") for i in x])

In [28]:
movies.head()

                                         genres  ...                crew
0  [Action, Adventure, Fantasy, ScienceFiction]  ...      [JamesCameron]
1                  [Adventure, Fantasy, Action]  ...     [GoreVerbinski]
2                    [Action, Adventure, Crime]  ...         [SamMendes]
3              [Action, Crime, Drama, Thriller]  ...  [ChristopherNolan]
4           [Action, Adventure, ScienceFiction]  ...     [AndrewStanton]

[5 rows x 7 columns]

In [29]:
movies['tag']=movies['overview']+movies['genres']+movies['keywords']+movies['cast']+movies['crew']

In [30]:
movies.head()

                                         genres  ...                                                tag
0  [Action, Adventure, Fantasy, ScienceFiction]  ...  [In, the, 22nd, century,, a, paraplegic, Marin...
1                  [Adventure, Fantasy, Action]  ...  [Captain, Barbossa,, long, believed, to, be, d...
2                    [Action, Adventure, Crime]  ...  [A, cryptic, message, from, Bond’s, past, send...
3              [Action, Crime, Drama, Thriller]  ...  [Following, the, death, of, District, Attorney...
4           [Action, Adventure, ScienceFiction]  ...  [John, Carter, is, a, war-weary,, former, mili...

[5 rows x 8 columns]

In [31]:
new_df=movies[['id','title','tag']]

In [32]:
new_df.head()

       id                                     title                                                tag
0   19995                                    Avatar  [In, the, 22nd, century,, a, paraplegic, Marin...
1     285  Pirates of the Caribbean: At World's End  [Captain, Barbossa,, long, believed, to, be, d...
2  206647                                   Spectre  [A, cryptic, message, from, Bond’s, past, send...
3   49026                     The Dark Knight Rises  [Following, the, death, of, District, Attorney...
4   49529                               John Carter  [John, Carter, is, a, war-weary,, former, mili...

In [33]:
new_df['tag']=new_df['tag'].apply(lambda x:" ".join(x))

C:\Users\Rahul paul\AppData\Local\Temp\ipykernel_13480\4079141722.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tag']=new_df['tag'].apply(lambda x:" ".join(x))

In [34]:
new_df['tag']=new_df['tag'].apply(lambda x: x.lower())

C:\Users\Rahul paul\AppData\Local\Temp\ipykernel_13480\2370209156.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tag']=new_df['tag'].apply(lambda x: x.lower())

In [35]:
new_df['tag']

0       in the 22nd century, a paraplegic marine is di...
1       captain barbossa, long believed to be dead, ha...
2       a cryptic message from bond’s past sends him o...
3       following the death of district attorney harve...
4       john carter is a war-weary, former military ca...
                              ...
4804    el mariachi just wants to play his guitar and ...
4805    a newlywed couple's honeymoon is upended by th...
4806    "signed, sealed, delivered" introduces a dedic...
4807    when ambitious new york attorney sam is sent t...
4808    ever since the second grade when he first saw ...
Name: tag, Length: 4806, dtype: object

In [40]:
import nltk

In [41]:
from nltk.stem.porter import PorterStemmer
ps=PorterStemmer()

In [42]:
def stem(text):
    y=[]
    for i in text.split():
        y.append(ps.stem(i))
    return " ".join(y)

In [43]:
new_df['tag']=new_df['tag'].apply(stem)

C:\Users\Rahul paul\AppData\Local\Temp\ipykernel_13480\599176683.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tag']=new_df['tag'].apply(stem)

In [44]:
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer(max_features=5000,stop_words='english')

In [45]:
vectors=cv.fit_transform(new_df['tag']).toarray()

In [46]:
from sklearn.metrics.pairwise import cosine_similarity

In [49]:
similarity=cosine_similarity(vectors)

In [52]:
def recommender (movie):
    movie_index= new_df[new_df['title']==movie].index[0]
    distance=similarity[movie_index]
    movie_list=sorted(list(enumerate(distance)),reverse=True,key=lambda x:x[1])[1:6]

    for i in movie_list:
        print(new_df.iloc[i[0]].title)

In [57]:
recommender('Batman Begins')

The Dark Knight
Batman
Batman
The Dark Knight Rises
10th & Wolf

In [59]:
import pickle

In [62]:
pickle.dump(new_df.to_dict(),open('movies_dict.pkl','wb'))

In [63]:
pickle.dump(similarity,open('similarity.pkl','wb'))